config/routes.rb
Taskmanager::Application.routes.draw do
  root to: 'home#index'
  get "home/index"

  devise_for :users

  resources :users

  resources :projects do
    resources :tasks
    resources :projects_users, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can [:create], Project
    can [:read], Project do |project|
      project.projects_users.pluck(:user_id).include?(user.id)
    end
    can [:read, :update, :destroy], Project, owner_id: user.id
    can [:create], Task
    can [:read, :update, :destroy], Task do |task|
    	#binding.pry   
      user.projects_users.pluck(:project_id).include?(task.project_id) ||
      user.own_projects.pluck(:id).include?(task.project_id)
    end

  end

end  

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	has_and_belongs_to_many :tasks
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :projects_users
  has_many :users, through: :projects_users
  has_many :tasks

  accepts_nested_attributes_for :tasks
  accepts_nested_attributes_for :projects_users

  validates :name, presence: true, length: { in: 3..50}, uniqueness: { scope: :owner_id}

  scope :sort_by_name, -> {order name: :asc}
  
end

app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  
  validates_associated :project
	validates :name, presence: true, length: { in: 3..50}

	has_many :attachments
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  has_many :projects_users
  has_many :own_projects, foreign_key: 'owner_id', class_name: Project
  has_many :projects, through: :projects_users
  has_many :tasks


  accepts_nested_attributes_for :projects_users

	validates :name, presence: true, length: { in: 3..50}, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/users_tasks.rb
class UsersTasks < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to projects_path
    else
      render new_user_session_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource param_method: :project_params

  def index
    @own_projects = current_user.own_projects.sort_by_name
    
    if !current_user.projects_users.empty?
      @assign_projects = Project.find_all_by_id(current_user.projects_users.pluck(:project_id))
    end
    @user_has_assign_projects = current_user.projects_users.pluck(:user_id).include?(current_user.id)
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find_by(id: params[:id])
    @tasks = @project.tasks
    @projectOwnerEmail = User.find_by(id: @project.owner_id).email
  end

  def edit
  end

  def create
    @project = Project.create(project_params)
    if @project.update(project_params.merge({owner_id: current_user.id}))
       current_user.own_projects << @project
       redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
       redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project
      @project = Project.find(params[:id])
  end

end

app/controllers/projects_users_controller.rb
class ProjectsUsersController < ApplicationController

  before_action :set_project

  def new
    @projects_user = ProjectsUser.new
    @projectList = User.all.map { |r|
      next if current_user.name==r.name || 
      r.projects_users.pluck(:project_id).include?(@project.id)
      [r.name, r.id] }
      @projectList = @projectList.compact
  end

  def create
    @projects_user = @project.projects_users.new(projects_users_params)
    if @projects_user.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end



  private

  def projects_users_params
    params.require(:projects_user).permit(:user_id)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_project, :find_task
  
  load_and_authorize_resource param_method: :task_params

  def new
    @task = Task.new
    authorize! :read, @project
  end

  def show
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def update
    @task.update(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project)
  end

  private

  def find_task
    @task = @project.tasks.find_by(id: params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def idex
  if user_signed_in?
    redirect_to projects_path
  else
    render new_user_session_path
  end
end

def update
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Taskmanager" %></title>
    <%= csrf_meta_tags %> 
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p> 

  <%= yield %>

  </body>
</html>

app/views/projects/edit.html.erb
<div class="popup-container">

<h2>Edit project</h2>

<%= simple_form_for @project do |f| %>
    <p>Current Name: "<strong><%= @project.name %> </strong>"<br></p>
    <%= f.input :name %>
    <div class="clearfix">
    	<%= f.button :submit, class:"pull-right btn-info"  %>
    </div>
<% end %>
<div class="links-row">
	<%= link_to '← Back to Projects', projects_path %>
</div>
</div>

app/views/projects/index.html.erb
<div class="project-container container">
<ul class="main-menu">
  <li>
    <%= link_to 'Edit my profile', edit_user_registration_path %>
  </li>
  <li>
    <%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class:"btn pull-right" %>
  </li>
</ul>

<h2>My Projects</h2>
<ul class="proj-info-list">
  <li><b>Hello, <%= current_user.name %>!</li>
</ul>

  <table class="table project-table">
<% if @own_projects.empty?  && !@user_has_assign_projects %>
  <tr>
    <td colspan="4">
      <center>
      <br>    
      <h4>You don't have any projects yet</h4>
      <br>
      <%= link_to 'Create Project', new_project_path, class:"btn btn-info" %>
      <br>
      <br>    
      </center>
    </td>
  </tr>
<% else %>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="2">
        <div class="pull-right">
        <%= link_to 'Create new project', new_project_path %>
        </div> 
      </th>
    </tr>   
    <% @own_projects.each do |p| %>
        <tr>
          <td class="col-id"><%= p.id %></td>
          <td class="col-name">
            <%= link_to p.name, project_path(p) %></td>
          <td class="col-edit"> 
            <%= link_to 'Edit', edit_project_path(p) %>
          </td>
          <td class="col-delete"> 
            <%= link_to 'Delete', p, method: :delete %>
          </td>
        </tr>
    <% end %>
<% end %>
  <% if @user_has_assign_projects %>
  <% @assign_projects.each do |p| next if current_user.id == p.owner_id %>
      <tr>
        <td class="col-id"><%= p.id %></td>
        <td class="col-name">
          <%= link_to p.name, project_path(p) %></td>
        <td class="col-edit">
        </td>
        <td class="col-delete">
        </td>
      </tr>
  <% end %>
  <% else %>
<% end %>  
</table>
</div>

app/views/projects/new.html.erb
<div class="popup-container">

<h2>Create new project</h2>

<%= simple_form_for @project do |f| %>
    <%= f.input :name %>
    <div class="clearfix">
    	<%= f.button :submit, class:"pull-right btn-info"  %>
    </div>
<% end %>
<div class="links-row">
	<%= link_to '← Back to Projects', projects_path %>
</div>
</div>

app/views/projects/show.html.erb
<div class="project-container container">
<ul class="main-menu">
  <li>
    <%= link_to '← Back to Projects', projects_path %>
  </li>
  <% if !@project.projects_users.pluck(:user_id).include?(current_user.id) %>
  <li>|</li>
  <li><%= link_to 'Share Project', new_project_projects_user_path(@project) %></li>
  <% end %>
  <li>
    <%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class:"btn pull-right" %>
  </li>
</ul>
<h2><%= @project.name %></h2>
<ul class="proj-info-list">
  <li><b>Creator's email:</b> <%= @projectOwnerEmail %></li>
</ul>

<table class="table tasks-table">
<th class="col-id">Id</th>
<th class="col-name">Name</th>
<th colspan="2" class="col-desc">
	<%= link_to 'Add New task', new_project_task_path(@project.id), class:"pull-right" %>
	Short Description
 </th>
	<% @tasks.each do |task| %>
		<tr>
			<td><%= task.id %></td>
			<td><%= link_to task.name, project_task_path(@project.id, task.id) %></td>
			<td><%= task.description %></td>
		</tr>
	<% end %>
</table>

<div>
</div>
</div>

app/views/projects_users/new.html.erb
<div class="popup-container">

<h2>Add user to project</h2>

<%= simple_form_for [@project, @projects_user] do |f| %>
	<%= f.select :user_id, @projectList %>
	<div class="clearfix">
		<%= f.submit "Add User", class:"btn pull-right btn-info" %>
	</div>
<% end %>
<div class="links-row">
	<%= link_to '← Back to Projects', projects_path %>
</div>
</div>

app/views/tasks/edit.html.erb
<div class="popup-container">

<h2>Edit task</h2>

<%= simple_nested_form_for [@project, @task] do |f| %>
	  <%= f.input :name, required: true %>
	  <%= f.input :description, as: :text %>
    <div class="clearfix">
    <%= f.button :submit, class:"pull-right btn-info"  %>
    </div>
<% end %>
<div class="links-row">
	<%= link_to '← Back to Projects', projects_path %>
</div>
</div>

app/views/tasks/new.html.erb
<div class="popup-container">

<h2>Create task</h2>

<%= simple_nested_form_for [@project, @task] do |f| %>
	  <%= f.input :name, required: true %>
	  <%= f.input :description, as: :text %>
    <div class="clearfix">
    <%= f.button :submit, class:"pull-right btn-info"  %>
    </div>
<% end %>
<div class="links-row">
	<%= link_to '← Back to Projects', projects_path %>
</div>
</div>

app/views/tasks/show.html.erb
<div class="project-container container">
	<ul class="main-menu">
		<li><%= link_to '← Back to Project', project_path(@project) %></li>
	  <li>
	    <% if user_signed_in? %>
	    <%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class:"btn pull-right" %>
	    <% end %>
	  </li>
	</ul>
	<h2><%= @project.name %></h2>

	<div class="task-container">
		<div class="row-fluid">
			<div class="span8">

				<h2><%= @task.name %></h2>
				<p><%= @task.description %></p>
			</div>
			<div class="span4 task-info">
				<h5>Task information</h5>
				<p><span>Created at: </span><%= @task.created_at %></p>
				<p><span>Updated at: </span><%= @task.updated_at %></p>
				<ul class="task-buttons-row">
					<li><%= link_to 'Delete task', p, method: :delete, class:"btn btn-danger" %></li>
					<li><%= link_to 'Edit task', edit_project_task_path, class:"btn btn-success" %></li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="popup-container congrat">
	<h2>Congratulations!</h2>
		<center>
			<%= link_to 'Go to my Projects', projects_path, class:"btn btn-info" %>
		</center>
</div>